.PHONY: clean All

All:
	@echo "----------Building project:[ Pentas_darbas - Debug ]----------"
	@cd "Pentas_darbas" && "$(MAKE)" -f  "Pentas_darbas.mk"
clean:
	@echo "----------Cleaning project:[ Pentas_darbas - Debug ]----------"
	@cd "Pentas_darbas" && "$(MAKE)" -f  "Pentas_darbas.mk" clean
